# Generated by Django 4.2.3 on 2023-07-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_quiz_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='score',
        ),
        migrations.AddField(
            model_name='point',
            name='general_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
