# Generated by Django 4.2.3 on 2023-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_quiz_questions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
