# Generated by Django 4.2.3 on 2023-07-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_quiz_created_at_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
