# Generated by Django 4.2.3 on 2023-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_point_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='school',
            field=models.CharField(default='', max_length=120),
        ),
    ]
