# Generated by Django 4.2.3 on 2023-10-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_countdowntimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdowntimer',
            name='status',
        ),
    ]
