# Generated by Django 4.2.3 on 2023-10-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_countdowntimer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdowntimer',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='countdowntimer',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
