# Generated by Django 4.2.3 on 2023-11-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_countdowntimer_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdowntimer',
            name='q_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='countdowntimer',
            name='q_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
