# Generated by Django 4.2.3 on 2023-11-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_countdowntimer_q_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdowntimer',
            name='q_end_time',
        ),
        migrations.RemoveField(
            model_name='countdowntimer',
            name='q_start_time',
        ),
        migrations.CreateModel(
            name='CountdownTimer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_start_time', models.DateTimeField(null=True)),
                ('q_end_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
